sudo: required
services: docker
language: bash

branches:
  only:
    - unknown

env:
  global:
    - DOCKER_REPO=siji

  matrix:
    - NAME=frp
    - NAME=privoxy
    - NAME=ss
    - NAME=v2ray

before_script:
  - docker build -t $DOCKER_REPO/$NAME:latest $NAME

script:
  - |
    if [[ $TRAVIS_EVENT_TYPE == "cron" ]]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      docker push $DOCKER_REPO/$NAME:latest
    fi
