name: CRON - build images

on: workflow_dispatch
# on:
#   workflow_dispatch: {}
#   schedule:
#   - cron: '1 1 * * 6'
#   push:
#     branches:
#     - master

env:
  QUAY_REGISTRY: quay.io
  DOCKER_REGISTRY: docker.io

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        name:
        - ddns
        - clash
        - v2ray
        - samba
        - nfs-server
    name: build images
    runs-on: ubuntu-latest

    steps:

    - name: checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: install podman
      run: |
        sudo apt update
        sudo apt -y install podman qemu-user-static

    - name: quay login
      uses: redhat-actions/podman-login@v1
      with:
        registry: ${{ env.QUAY_REGISTRY }}
        username: ${{ secrets.QUAY_USER }}
        password: ${{ secrets.QUAY_TOKEN }}

    - name: docker login
      uses: redhat-actions/podman-login@v1
      with:
        registry: ${{ env.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: build and push image
      run: |
        podman build --platform linux/arm64,linux/amd64 --manifest ${{ matrix.name }}:latest ${{ matrix.name }}
        podman manifest push --all ${{matrix.name}}:latest ${{ env.QUAY_REGISTRY }}/siji/${{matrix.name}}:latest
        podman manifest push --all ${{matrix.name}}:latest ${{ env.DOCKER_REGISTRY }}/siji/${{matrix.name}}:latest
