name: CRON - build images

on:
  workflow_dispatch: {}
  schedule:
  - cron: '1 1 * * 6'
  push:
    branches:
    - master

env:
  QUAY_REGISTRY: quay.io
  DOCKER_REGISTRY: docker.io

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        name:
        - privoxy
        - v2ray
    name: build images
    runs-on: ubuntu-latest

    steps:

    - name: checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: build image
      uses: redhat-actions/buildah-build@v2
      with:
        image: quay.io/siji/${{ matrix.name }}
        tags: latest
        archs: amd64, arm64
        containerfiles: |
          ${{ matrix.name }}/Dockerfile

    - name: push image
      uses: redhat-actions/push-to-registry@v2
      with:
        image: quay.io/siji/${{ matrix.name }}
        tag: latest
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
        registry: ${{ env.DOCKER_REGISTRY }}
